changelog:
  categories:
    - title: "What's changed"
      labels:
        - "*"
    - title: "Breaking changes"
      labels:
        - breaking changes
    
    - title: "New features"
      labels:
        - feature
